version: "3.9"
services:
  et-db:
    container_name: et-db
    image: postgres:alpine
    environment:
      POSTGRES_USER: dmitri
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_MULTIPLE_DATABASES: einstufungstest, exams
      PGDATA: /data/postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres-et-db:/var/lib/data/postgres
    ports:
      - "5433:5432"
    networks:
      - et-ntwk
      - et-management
    restart: unless-stopped


  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
      - et-ntwk
    ports:
      - "9411:9411"

  et-api-gateway:
    image: dmitriikonnovnn/et-apigateway:1.1-SNAPSHOT
    container_name: et-api-gateway
    ports:
      - "80:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker-eureka
    networks:
      - et-ntwk
      - et-management
    depends_on:
      - zipkin
      - et-eureka-server
  et-eureka-server:
    container_name: et-eureka-server
    image: dmitriikonnovnn/et-eureka-server:1.1-SNAPSHOT
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker-eureka
    networks:
      - et-ntwk
    depends_on:
      - zipkin

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  einstufungstest:
    image: dmitriikonnovnn/einstufungs-test:2.0-SNAPSHOT
    container_name: einstufungstest
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker-eureka
      JVM_OPTS: >
        -Xmx250M
        -Xms180M
    networks:
      - et-ntwk
    depends_on:
      - et-db
      - zipkin
      - et-eureka-server
      - et-api-gateway

  et-management:
    image: dmitriikonnovnn/et-management:1.0-SNAPSHOT
    container_name: et-management
    ports:
      - "8087:8087"
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker-eureka
      JVM_OPTS: >
        -Xmx250M
        -Xms180M
    networks:
      - et-management
      - et-ntwk
    depends_on:
      - et-db
      - zipkin
      - et-eureka-server
      - et-api-gateway

networks:
  et-ntwk:
    driver: bridge
  et-management:
    driver: bridge

volumes:
  postgres-et-db: