global:
  scrape_interval: 15s
  evaluation_interval: 15s # evaluate rules every 15 seconds

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'einstufungs-test'
    metrics_path: 'actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9002']
