spring:
  profiles:
    active: local, localdocker, local-k8s, aws-prod, aws-test, aws-k8s, docker-eureka

---

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.name@
app:
  userService:
    tokenExpirationTime: 5
    maxTokenExpirationTime:
      min: 60
      hours: 24
      days: 30
  jwt:
    token:
      secretKey: P@s$w0rDP@ssw0rdP@s$w0rDP@ssw0rdP@s$w0rDP@ssw0rd
  security:
    webSecurityAdapterQualifier: permitAll
    daoAuthenticationProvider: inDataBase
aws:
  s3:
    region:
      name: us-east-1
server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8087
spring:
  config:
    activate:
      on-profile: local
  datasource:
    password: P@ssw0rd
    url: jdbc:mysql://localhost:3306/et-neu?createDatabaseIfNotExist=true&Unicode=true&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  second-datasource:
  #    password:
  #    url:
  #    username:
  #    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          lob:
            non_contextual_creation: true
        generate-statistics: true
        format_sql: true
        show-sql: true
        use_sql_comments: true
        query:
          in_clause_parameter_padding: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 3
        search:
          version: 5.11.7.Final
  application:
    name: et-management
  zipkin:
    base-url: http://zipkin:9411
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
mailgun:
  api:
    privatekey:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
    enabled: false
  instance:
    hostname: et-management

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
      status:
        order: out-of-service, down, up