spring:
  profiles:
    active: local, localdocker, local-k8s, aws-prod, aws-test, aws-k8s

---

info:
  app:
    name: Einstufungstest Verwaltung
    description: none
    version: snapshot 1.0

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
spring:
  config:
    activate:
      on-profile: local
  datasource:
    password: P@ssw0rd
    url: jdbc:mysql://localhost:3306/einstufungs-test?createDatabaseIfNotExist=true&Unicode=true&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  second-datasource:
  #    password:
  #    url:
  #    username:
  #    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          lob:
            non_contextual_creation: true
        generate-statistics: true
        format_sql: true
        show-sql: true
        use_sql_comments: true
        query:
          in_clause_parameter_padding: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 3
        search:
          version: 5.11.7.Final