spring:
  profiles:
    active: local, localdocker, docker-eureka, local-k8s, aws-prod, aws-test, aws-k8s

---

info:
  app:
    name: Einstufungstest Application
    description: none
    version: snapshot 2.0

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
spring:
  config:
    activate:
      on-profile: local
  datasource:
    password: P@ssw0rd
    url: jdbc:mysql://localhost:3306/einstufungs-test?createDatabaseIfNotExist=true&Unicode=true&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  second-datasource:
#    password:
#    url:
#    username:
#    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          lob:
            non_contextual_creation: true
        generate-statistics: true
        format_sql: true
        show-sql: true
        use_sql_comments: true
        query:
          in_clause_parameter_padding: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 3
        search:
          version: 5.11.7.Final
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
sentry:
  dsn: https://572fc37d0c98457293eedeabfceb7612@o1319089.ingest.sentry.io/6574242
  in-app-includes: solutions.dmitrikonnov.einstufungstest


#logging:
#  level:
#    org:
#      hibernate:
#        stat: debug
#        SQL: TRACE
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#  file:
#    path: ./logs

debug: true

---


info:
  app:
    name: Einstufungstest Application
    description: none
    version: snapshot 2.0

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
spring:
  config:
    activate:
      on-profile: localdocker
  datasource:
    password: P@ssw0rd
    url: jdbc:mysql://host.docker.internal:3306/einstufungs-test?createDatabaseIfNotExist=true&Unicode=true&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  second-datasource:
  #    password:
  #    url:
  #    username:
  #    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          lob:
            non_contextual_creation: true
        generate-statistics: true
        format_sql: true
        show-sql: true
        use_sql_comments: true
        query:
          in_clause_parameter_padding: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 3
        search:
          version: 5.11.7.Final

sentry:
  dsn: https://572fc37d0c98457293eedeabfceb7612@o1319089.ingest.sentry.io/6574242
  in-app-includes: solutions.dmitrikonnov.einstufungstest


#logging:
#  level:
#    org:
#      hibernate:
#        stat: debug
#        SQL: TRACE
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#  file:
#    path: ./logs

debug: true

---

info:
  app:
    name: Einstufungstest Application
    description: none
    version: snapshot 2.0

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
spring:
  config:
    activate:
      on-profile: aws-test
  datasource:
    password: 5J2X!Bf2s_d9Hj2
    url: jdbc:postgresql://aamyheif84t424.ckswrjm0ier7.us-east-2.rds.amazonaws.com:5432/einstufungstest
    username: ETBDUser
    driver-class-name: org.postgresql.Driver
  #  second-datasource:
  #    password:
  #    url:
  #    username:
  #    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        search:
          version: 5.11.7.Final
sentry:
  dsn: https://572fc37d0c98457293eedeabfceb7612@o1319089.ingest.sentry.io/6574242
  in-app-includes: solutions.dmitrikonnov.einstufungstest


---


info:
  app:
    name: Einstufungstest Application
    description: none
    version: snapshot 2.0

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
spring:
  application:
    name: einstufungstest
  config:
    activate:
      on-profile: docker-eureka
  zipkin:
    base-url: http://zipkin:9411
  datasource:
    password: P@ssw0rd
    url: jdbc:postgresql://einstufungstest-db:5432/customer
    username: root
    driver-class-name: org.hibernate.dialect.PostgreSQLDialect
  #  second-datasource:
  #    password:
  #    url:
  #    username:
  #    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        generate-statistics: true
        format_sql: true
        show-sql: true
        use_sql_comments: true
        query:
          in_clause_parameter_padding: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 3
        search:
          version: 5.11.7.Final

sentry:
  dsn: https://572fc37d0c98457293eedeabfceb7612@o1319089.ingest.sentry.io/6574242
  in-app-includes: solutions.dmitrikonnov.einstufungstest
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true